# Generated by Django 3.2.5 on 2022-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('IID', models.CharField(max_length=40)),
                ('reference', models.URLField(max_length=40)),
                ('original_image', models.ImageField(upload_to='')),
                ('data_text', models.FileField(upload_to='GraphDataTXT/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
